steps:
  - read: name
    from: env.name
    fallback:
      from: git.name
      fallback:
        prompt: "Enter the pretty URL for the module."

  - read: module_name
    from: env.module_name
    fallback:
      from: git.module_name
      fallback:
        prompt: "Enter the module name, starting with the prefix \"pr_\"."

  - read: module_type
    from: env.module_type
    fallback:
      from: git.module_type
      fallback:
        prompt: "Enter the module type. Available options are: \"shared\", \"client\", \"server\". Default: \"shared\""

  - read: install_directory
    from: env.install_directory
    fallback:
      from: git.install_directory
      fallback:
        prompt: "Where should the module be installed to? Default: \"modules/\""

  - read: release_directory
    from: env.release_directory
    fallback:
      from: git.release_directory
      fallback:
        prompt: "The directory that should be used for GitHub releases."

  - read: git_url
    from: env.git_url
    fallback:
      from: git.git_url
      fallback:
        prompt: What is the git clone URL for the repository?

  - read: github_url
    from: env.github_url
    fallback:
      from: git.github_url
      fallback:
        prompt: What is the GitHub URL for the repository?

  - copy: README.tmpl.md
    to: README.md
  - copy: Install.cmake.tmpl
    to: Install.cmake
  - copy: src/pr_module.cpp.tmpl
    to: src/pr_module.cpp
  - copy: .github/pragma_module_info.json.tmpl
    to: .github/pragma_module_info.json
  - copy: examples/ex_load_pragma_module.tmpl.lua
    to: examples/ex_load_pragma_module.lua

  - write: |
      module_type raw: {{ module_type }}
      module_type_norm: {{ module_type | trim | lowercase }}
      match_shared: {{ module_type | matches: "(?i)^shared$" }}
      match_client: {{ module_type | matches: "(?i)^client$" }}
      match_server: {{ module_type | matches: "(?i)^server$" }}
    to: tmplr-debug.txt

  - if:
      eval: '{{ module_type | matches: server }}'
    copy: CMakeLists.server.txt.tmpl
    to: CMakeLists.txt
    else:
      if:
        eval: '{{ module_type | matches: client }}'
      copy: CMakeLists.client.txt.tmpl
      to: CMakeLists.txt
      else:
        copy: CMakeLists.shared.txt.tmpl
        to: CMakeLists.txt

  - remove: README.tmpl.md
  - remove: Install.cmake.tmpl
  - remove: src/pr_module.cpp.tmpl
  - remove: .github/pragma_module_info.json.tmpl
  - remove: CMakeLists.shared.txt.tmpl
  - remove: CMakeLists.server.txt.tmpl
  - remove: CMakeLists.client.txt.tmpl
  - remove: template_pragma_module.json
  - remove: examples/ex_load_pragma_module.tmpl.lua
  - remove: .gitignore
  - remove: github_actions
